<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-SDLQ3M27" failures="0" tests="3" name="COM.SELENIUM.TOPICS._39_TestNGExpectedException" time="18.404" errors="0" timestamp="2021-01-20T21:50:44 IST" skipped="0">
  <testcase classname="COM.SELENIUM.TOPICS._39_TestNGExpectedException" name="TestCase_2" time="6.037"/>
  <system-out/>
  <testcase classname="COM.SELENIUM.TOPICS._39_TestNGExpectedException" name="TestCase_3" time="6.129"/>
  <system-out/>
  <testcase classname="COM.SELENIUM.TOPICS._39_TestNGExpectedException" name="TestCase_1" time="6.238"/>
  <system-out/>
</testsuite> <!-- COM.SELENIUM.TOPICS._39_TestNGExpectedException -->
